version: '3'
volumes:
  dbtest: {}

services:
  db:
    image: mdillon/postgis
    volumes:
      - dbtest:/var/lib/postgresql-data
    environment:
      - POSTGRES_DB=taxis
  api:
    volumes:
      - ./containers/api/test_settings.py:/settings.py
      - python-venv-cache-api:/venv/
      - ./projects/APITaxi:/git/APITaxi
      - ./projects/APITaxi_models:/git/APITaxi_models
      - ./projects/APITaxi_utils:/git/APITaxi_utils
      - ./projects/ZUPC:/tmp/ZUPC
    environment:
      - TEST_POST_URL=http://minimal-operateur-server:5000
