version: '3'

volumes:
  db: {}
  python-venv-cache: {}

services:
  db:
    container_name: db
    image: mdillon/postgis
    volumes:
      - db:/var/lib/postgresql-data

  redis:
    container_name: redis
    image: redis

  api:
    container_name: api
    image: le.taxi/api
    volumes:
      - ./containers/api/settings.py:/settings.py
      - python-venv-cache:/venv/
      - ./projects/APITaxi:/git/APITaxi
      - ./projects/APITaxi_models:/git/APITaxi_models
      - ./projects/APITaxi_utils:/git/APITaxi_utils
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'
