version: '3'

volumes:
  db: {}
  python-venv-cache-api: {}
  python-venv-cache-worker: {}
  python-venv-cache-front: {}
  python-venv-cache-geofaker: {}

services:
  db:
    image: mdillon/postgis
    volumes:
      - db:/var/lib/postgresql-data

  redis:
    image: redis

  api:
    image: le.taxi/api
    volumes:
      - ./containers/api/settings.py:/settings.py
      - python-venv-cache-api:/venv/
      - ./projects/APITaxi:/git/APITaxi
      - ./projects/APITaxi_models:/git/APITaxi_models
      - ./projects/APITaxi_utils:/git/APITaxi_utils
      - ./projects/ZUPC:/tmp/ZUPC
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'

  worker:
    image: le.taxi/worker
    volumes:
      - ./containers/api/settings.py:/settings.py
      - python-venv-cache-worker:/venv/
      - ./projects/APITaxi:/git/APITaxi
      - ./projects/APITaxi_models:/git/APITaxi_models
      - ./projects/APITaxi_utils:/git/APITaxi_utils

  front:
    image: le.taxi/front
    volumes:
      - ./containers/front/settings.py:/settings.py
      - python-venv-cache-front:/venv/
      - ./projects/APITaxi:/git/APITaxi
      - ./projects/APITaxi_models:/git/APITaxi_models
      - ./projects/APITaxi_utils:/git/APITaxi_utils
      - ./projects/APITaxi_front:/git/APITaxi_front
    ports:
      - '5101:5000'

  geotaxi:
    image: le.taxi/geotaxi
    volumes:
      - ./projects/GeoTaxi:/git/geotaxi
    depends_on:
      - redis
    ports:
      - '8080:8080'

  geofaker:
    image: le.taxi/geofaker
    volumes:
      - python-venv-cache-geofaker:/venv/
      - ./projects/geofaker:/git/geofaker
    depends_on:
      - geotaxi
