#!/bin/bash
#set -e
set -v

if [[ $# != 1 ]];
then
  echo "Usage: $0 <dump>"
  exit 1
fi

docker-compose stop api worker

export PGHOST=localhost
export PGPORT=55432
export PGUSER=postgres
export PGDATABASE=taxis

dropdb $PGDATABASE || exit 1
createdb $PGDATABASE
createuser u3ysn4tyqbzcvon9cocq || true

psql -c 'CREATE EXTENSION IF NOT EXISTS timescaledb;'
psql -c 'SELECT timescaledb_pre_restore();'

pg_restore -d $PGDATABASE $1 || true

psql -c 'SELECT timescaledb_post_restore();'

# neotaxi is the account used by the simulator, but not activated in prod
docker-compose exec api bash -c 'flask create_user --password a neotaxi operateur moteur'

docker-compose start api worker

# the following steps are not automated
echo "* Peut-être faut-il appliquer des migrations..."
# to do this, use an admin account on the console, "administration" tab, find and switch to the neotaxi account
# then "mon compte", and set the URL below in the "URL de votre API" field.
echo "* Changer l'endpoint de neotaxi pour http://minimal-operateur-server:5000/hail !"
